# Generated by Django 4.1.6 on 2023-08-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Relationship', '0002_comments_alter_userrelationship_followed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post',
        ),
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='file',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
