# Generated by Django 4.1.6 on 2023-08-26 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Relationship', '0006_alter_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='original_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='User_Relationship.posts'),
        ),
    ]
